### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by QiyaoWei** [rohithaug/sepsis-prediction#1]
Dear authors,

Hope this message finds you well, and many thanks for your work on using MIMIC-IV. It seems like this repo is missing a couple of data files (from sagemaker), hindering the reproducibility of this repo. Could the authors kindly upload the data files corresponding to this repo? Many thanks!

**Comment by rohithaug** [comment]
Hi @QiyaoWei, the data is available at https://physionet.org/content/mimic-cxr/2.0.0/ as mentioned in the report. You can refer it for details on how to access the data.
